name: Run the Archiverepo

on:
 push:
    branches:
      - "**/*"
 pull_request:
    
      

env:
  CURRENT_PR_REPO: "${{ github.repository }}"
  GIT_TOKEN: "${{ github.token }}"
  CURRENT_PR_NUMBER: "${{ github.event.pull_request.number }}"
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: check the pull request gets merged
      run: echo "pull request status:${{github.event.pullrequest.merged}}"
    - name: Checkout the repository source code
      uses: actions/checkout@v2
    - run: sudo apt-get update -y
    - run: sudo apt install -y jq
    - run: jq --version
    - run: chmod +x ./transfer_repo.sh
    - run: ./transfer_repo.sh ${{ env.GIT_TOKEN }} ${{ env.CURRENT_PR_REPO }} ${{ env.CURRENT_PR_NUMBER }}
      shell: bash
